import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Children } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface NavigationText {
  children: React.ReactNode;
}

const NavigationText: React.FC<NavigationText> = ({ children }) => {
  return (
    <>
      <li className=''>
        <div className='hover:text-red-700'>{children}</div>
      </li>
    </>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <meta title='Ore Ore Play Ground' />
      </head>
      <body className={`${inter.className}`}>
        {/* main header */}
        <header className='block justify-center items-center w-full'>
          <h1 className='bg-blue-300 h-10'>
            This site is a personal playground.
          </h1>

          {/* navigation */}
          {/* TODO：マウスホバー時のエフェクトをテキストカラーに加えてボタン全体の色変更を追加する */}
          {/* TODO：どのページにいるかでエフェクトを追加する（Github参考） */}
          <nav className='flex justify-start items-center h-10 bg-red-300'>
            <ul className='flex pl-2'>
              <div className='ml-4'>
                <NavigationText>
                  <Link href={"/"}>Home</Link>
                </NavigationText>
              </div>
              <div className='ml-4'>
                <NavigationText>
                  <Link href={"/nextjs"}>Next.js</Link>
                </NavigationText>
              </div>
              <div className='ml-4'>
                <NavigationText>
                  <Link href={"/atomic_design"}>Atomic Design</Link>
                </NavigationText>
              </div>
              <div className='ml-4'>
                <NavigationText>
                  <Link href={"tailwindcss"}>TailwindCSS</Link>
                </NavigationText>
              </div>
            </ul>
            <p className='ml-10 bg-slate-400'>なにかいれるかも</p>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
