import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Children } from "react";
import Link from "next/link";
import NavigationText from "../../component/atoms/text-hovered-color";
import LinkNavigationMenu from "../../component/molecules/link_navigation_menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <meta title='Ore Ore Play Ground' />
      </head>
      <body className={`${inter.className}`}>
        {/* main header */}
        <header className='block justify-center items-center w-full'>
          <h1 className='bg-blue-300 h-10'>
            This site is a personal playground.
          </h1>

          {/* navigation */}
          {/* TODO：マウスホバー時の色を調整する */}
          {/* TODO：どのページにいるかでエフェクトを追加する（Github参考） */}
          {/* TODO：Navigationメニューとメインコンテンツとの境界線を示す罫線を追加する */}
          <nav className='flex justify-start items-center h-10 bg-red-300'>
            <ul className='flex pl-2'>
              <LinkNavigationMenu link={"/"}>Home</LinkNavigationMenu>
              <LinkNavigationMenu link={"/nextjs"}>Next.js</LinkNavigationMenu>
              <LinkNavigationMenu link={"/atomic_design"}>
                Atomic Design
              </LinkNavigationMenu>
              <LinkNavigationMenu link={"/tailwindcss"}>
                TailwindCSS
              </LinkNavigationMenu>
            </ul>
            <p className='ml-10 bg-slate-400'>なにかいれるかも</p>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
