export const atomsList = [
  "テキスト（Text）",
  "ボタン（Button）",
  "リンク（Link）",
  "アイコン（Icon）",
  "イメージ（Image）",
  "インプットフィールド（Input field）",
  "チェックボックス（Checkbox）",
  "ラジオボタン（Radio button）",
  "セレクトボックス（Select box）",
  "スライダー（Slider）",
  "プログレスバー（Progress bar）",
  "スピナー（Spinner）",
  "タグ（Tag）",
  "アバター（Avatar）",
  "レーティング（Rating）",
  "アラート（Alert）",
  "バッジ（Badge）",
  "ラベル（Label）",
  "リストアイテム（List item）",
  "メニューアイテム（Menu item）",
];
