name: Docsearch Scraper Cron

on:
  schedule:
    - cron: '0 0 * * *' # この例では、毎日午前0時に実行されます。Cron式は任意に調整してください。

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure Docker CLI
      run: echo ${{ secrets.ENV_FILE_CONTENT }} > .env && echo ${{ secrets.CONFIG_JSON_CONTENT }} > config.json

    - name: Run Docsearch Scraper
      run: docker run -it --platform linux/amd64 --env-file=.env -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper
